/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/components/AboutView.vue')['default']
    HomeView: typeof import('./src/components/HomeView.vue')['default']
    LoginView: typeof import('./src/components/LoginView.vue')['default']
    MyeloidView: typeof import('./src/components/MyeloidView.vue')['default']
    PatientsView: typeof import('./src/components/PatientsView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
